import React, {
    Component
} from 'react';
import {
    AppRegistry,
    StyleSheet,
    Image,
} from 'react-native';
import UtilScreen from "../util/UtilScreen";

const Dimensions = require('Dimensions');
const {
    width,
    height
} = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        // backgroundColor: '#F5FCFF',
        backgroundColor:'white',
    },
    other_view:{
        marginTop:11,
        flexDirection:'row',
    },
    login_head_image:{
        marginTop:35,
        width:100,
        height:100,
        // marginLeft:138,
        alignSelf:'center',
        borderRadius:200,
        resizeMode: Image.resizeMode.stretch
    },
    textInputStyle:{
        fontSize:16,
        marginTop:8,
        color:'#cacaca',
        marginLeft:35,
        marginRight:35,
    },
    bigTextPrompt:{
        lineHeight:40,
        marginTop:33,
        marginLeft:25,
        marginRight:25,
        backgroundColor:'#ff9d00',
        color:'white',
        textAlign:'center',
        fontSize:16,
        height:40,
        borderRadius:6,
    },
    top_title_view:{
        flexDirection: "row",
        justifyContent:'center',
        alignItems:'center',
        width:width,
        height:44,
        backgroundColor:'#000'
    },
    top_title_back:{
        marginLeft:10,
        width:8,
        height:13,
        marginTop:3,
        position:'absolute',
        left:0,
    },
    top_title_text:{
        fontSize:16,
        color:'#fff',
    },
    login_register:{
        marginLeft:116,
        // marginRight:28,
        fontSize:16,
        color:'#f5a623',
    },
    login_divider:{
        marginLeft:28,
        height:19,
        alignSelf:'center',
        width:2,
    },
    login_get_pw:{
        marginLeft:28,
        fontSize:16,
    },
    login_wxlogin:{
        position:'absolute',
        bottom:0,
        fontSize:14,
        alignSelf:'center',
        color:'#cacaca',
    },
    login_otherlogin_view:{
        justifyContent:'center',
        width:'100%',
        marginTop:UtilScreen.getHeight(150),
        height:UtilScreen.getHeight(40),
        alignSelf:'center',
    },
    login_otherlogin_background:{
        position:'absolute',
        top:UtilScreen.getHeight(19),
        backgroundColor:'#cacaca',
        height:UtilScreen.getHeight(2),
        width:'100%',
    },
    login_otherlogin_wx:{
        backgroundColor:'#ffffff',
        height:UtilScreen.getHeight(45),
        width:UtilScreen.getWidth(45),
        alignSelf:'center',
    },
    login_wx_btn:{
        width:UtilScreen.getWidth(260),
        backgroundColor:'#ffffff',
        fontSize:14,
        color:'#cacaca',
        alignSelf:'center',
        textAlign:'center',
    },
    register_getcode:{
        flex:2,
        width:200,
        fontSize:16,
        color:'#cacaca',
        marginLeft:35,
    },
    register_getcode_text:{
        fontSize:16,
        color:'#ff9d00',
        textAlign:'right',
        marginRight:42,
        marginTop:16,
    },
    set_label_text:{
        position:'absolute',
        left:0,
        color:'#333333',
        marginLeft:20,
        fontSize:14,
        lineHeight:UtilScreen.getHeight(88),
        alignItems:'center',
    },
    set_label_view:{
        justifyContent:'center',
        alignItems:'center',
        marginTop:UtilScreen.getHeight(12),
        flexDirection:'row',
        height:UtilScreen.getHeight(88),
        backgroundColor:'#fff',
    },
    set_label_enter:{
        position:'absolute',
        right:0,
        marginRight:UtilScreen.getWidth(40),
        backgroundColor:'#ffffff',
        // width:UtilScreen.getWidth(50),
        // height:UtilScreen.getHeight(50),
        // borderRadius:UtilScreen.getHeight(80),
    },
    set_cache_text:{
        position:'absolute',
        right:0,
        marginRight:18,
        fontSize:14,
        color:'#333333',
    },
    set_logout:{
        textAlign:'center',
        position:'absolute',
        bottom:0,
        height:UtilScreen.getHeight(98),
        fontSize:15,
        backgroundColor:'#ff9d00',
        color:'#ffffff',
        width:width,
        lineHeight:UtilScreen.getHeight(98),
    },
    update_message:{
        alignItems:'center',
        marginTop:UtilScreen.getHeight(40),
        marginLeft:UtilScreen.getWidth(25),
        marginRight:UtilScreen.getWidth(25),
        height:UtilScreen.getHeight(80),
    },
    update_message_text:{
        lineHeight:UtilScreen.getHeight(80),
        fontSize:14,
        color:'#333333',
    },
    lightitem: {
        backgroundColor: '#fff'
    },
    line: {
        width: '100%',
        height: UtilScreen.getHeight(15),
        backgroundColor: '#f8f8f8',
    },
    paymentView:{
        width:UtilScreen.getWidth(700),
        marginLeft:UtilScreen.getWidth(24),
        marginRight:UtilScreen.getWidth(24),
        height:UtilScreen.getHeight(88),
       // position:'absolute',
       // bottom:UtilScreen.getHeight(40),
        marginBottom:UtilScreen.getHeight(40),
        backgroundColor:'#ff9d00',
        borderRadius:UtilScreen.getWidth(12),
        justifyContent:'center',
        alignItems:'center',
    },
    paymentText:{
        alignSelf:'center',
        color:'#ffffff',
        fontSize:18,
    },
    payView:{
        width:'100%',
       // position:'absolute',
       // bottom:UtilScreen.getHeight(140),
        marginBottom:UtilScreen.getHeight(10),
        height:UtilScreen.getHeight(242),
        flexDirection:'column',
    },
    payImage:{
        left:UtilScreen.getWidth(38),
        backgroundColor:'#fff',
        resizeMode:'contain',
        width:UtilScreen.getWidth(36),
        height:UtilScreen.getWidth(36),
        alignSelf:'center',
    },
    payText:{
        left:UtilScreen.getWidth(38),
        lineHeight:UtilScreen.getHeight(88),
        marginLeft:UtilScreen.getWidth(10),
        fontSize:14,
        color:'#333333',
        alignSelf:'center',
    },
    selectImage:{
        width:UtilScreen.getWidth(30),
        resizeMode:'contain',
        alignSelf:'center',
        position:'absolute',
        right:UtilScreen.getWidth(40),
    },
    selectView:{
        flexDirection:'row',
        height:UtilScreen.getHeight(76),
    },
    leftText: {
        marginTop:UtilScreen.getHeight(24),
        left:UtilScreen.getWidth(38),
        color: '#333',
        fontSize: 14,
        width:UtilScreen.getWidth(140),
        textAlign:'justify',
    },
    rightText:{
        position:'absolute',
        right:0,
        marginRight:UtilScreen.getWidth(64),
        color:'#333333',
    },
    light_F8F8F8:{
        marginTop:UtilScreen.getHeight(24),
        marginBottom:UtilScreen.getHeight(24),
      backgroundColor:'#f8f8f8',
      width:'100%',
      height:UtilScreen.getHeight(12),
    },
    light_E5E5E5:{
        marginTop:UtilScreen.getHeight(30),
        marginBottom:UtilScreen.getHeight(30),
        backgroundColor:'#e5e5e5',
        width:UtilScreen.getWidth(680),
        height:UtilScreen.getHeight(2),
        alignSelf:'center',
    },
    it_insertTextStyle:{
        fontSize:16,
        marginTop:UtilScreen.getHeight(40),
        marginLeft:UtilScreen.getWidth(40),
        color:'#333333',
    },
    it_stateStyle:{
        fontSize:14,
        marginTop:UtilScreen.getHeight(10),
        marginLeft:UtilScreen.getWidth(40),
        color:'#333333',
    },
    it_imageStyle:{
        alignSelf:'center',
        marginTop:UtilScreen.getHeight(20),
        width:UtilScreen.getWidth(680),
        height:UtilScreen.getHeight(453),
    },
    it_myView:{
        height:UtilScreen.getHeight(28),
        width:UtilScreen.getWidth(680),
        alignSelf:'center',
        flexDirection:'row',
    },
    it_smallImageStyle:{
        backgroundColor:'#ffffff',
        width:UtilScreen.getWidth(28),
        height:UtilScreen.getHeight(28),
        position:'absolute',
    },
    it_textStyle:{
        fontSize:12,
        color:'#333333',
        alignSelf:'center',
        position:'absolute',
    },
});